app = "zhorben-elysium-b8519e34-146a-4f58-be46-ba3f3111e01b"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'
DEPLOY_ID = 'e245c24c-97ca-4497-a25e-5b108d79e88d'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
